package com.payflex.campaignCriteria.drlGenerator;

import java.util.List;
import java.util.HashMap;

import tr.com.innova.payflex.campaignCriteria.drlGenerator.helpers.*;
import tr.com.innova.payflex.campaignCriteria.drlGenerator.entity.*;

//CampaignName : Scenario7

rule "Campaign(7)-Rule1-Sec1(Init)"
	when
		$event : DroolsCampaignEvent(getDroolsCampaignAuditByRuleNo(1) == DroolsCampaignAudit.NewEventReceived)
	then
		$event.updateDroolsCampaignAuditByRuleNo(1, DroolsCampaignAudit.DroolsCampaignEventValidated);
		update($event);
end

rule "Campaign(7)-Rule1-Sec2(EndUser)"
	when
		$event : DroolsCampaignEvent(getDroolsCampaignAuditByRuleNo(1) == DroolsCampaignAudit.DroolsCampaignEventValidated)
		eval
		(
			 $event.getEndUserField("Segment") == "VIP" && 
			 $event.getEndUserField("Gender") == "F" && 
			 DroolsDateHelper.IsDayOfYear($event.getEndUserField("Birthdate"), $event.getValue("Timestamp"))
		)
	then
		$event.updateDroolsCampaignAuditByRuleNo(1, DroolsCampaignAudit.EndUserCriteriasAreSatisfied);
		update($event);
end

rule "Campaign(7)-Rule1-Sec3(CurrentEvent)"
	when
		$event : DroolsCampaignEvent(getDroolsCampaignAuditByRuleNo(1) == DroolsCampaignAudit.EndUserCriteriasAreSatisfied)
		eval
		(
			 $event.getCurrentEventField("Type") == "Recharge" && 
			 DroolsDateHelper.firstIsAfterSecond($event.getCurrentEventField("Date"),"2016-12-01 00:00:00") && 
			 DroolsDateHelper.firstIsBeforeSecond($event.getCurrentEventField("Date"),"2017-01-01 00:00:00") && 
			 $event.getCurrentEventField("Amount") != null && (double)$event.getCurrentEventField("Amount") >= 100.0 && 
			 $event.getCurrentEventField("Amount") != null && (double)$event.getCurrentEventField("Amount") < 250.0
		)
	then
		$event.updateDroolsCampaignAuditByRuleNo(1, DroolsCampaignAudit.CurrentEventCriteriasAreSatisfied);
		update($event);
end

rule "Campaign(7)-Rule1-Sec4(PastEvents)"
	when
		$event : DroolsCampaignEvent(getDroolsCampaignAuditByRuleNo(1) == DroolsCampaignAudit.CurrentEventCriteriasAreSatisfied)

		$pastEvents0 : List()
				from collect(HashMap(
					get("Type") == "Purchase",
					DroolsHelper.firstArrayContainsSecond("1",get("Location")),
					get("Amount") >= 15,
					true
				)
				from $event.getPastEvents)
		eval(FrequencyHelper.checkFrequencyForPastEvents($event.getValue("Timestamp"), "2-MC", $pastEvents0, 1, 999999))

		$pastEvents1 : List()
				from collect(HashMap(
					get("Type") == "Recharge",
					get("Amount") >= 25,
					true
				)
				from $event.getPastEvents)
		eval(FrequencyHelper.checkFrequencyForPastEvents($event.getValue("Timestamp"), "2-MC", $pastEvents1, 2, 999999))
	then
		$event.updateDroolsCampaignAuditByRuleNo(1, DroolsCampaignAudit.PastEventsCriteriasAreSatisfied);
		update($event);
end

rule "Campaign(7)-Rule1-Sec5(PastBenefits)"
	when
		$event : DroolsCampaignEvent(getDroolsCampaignAuditByRuleNo(1) == DroolsCampaignAudit.PastEventsCriteriasAreSatisfied)
	then
		$event.updateDroolsCampaignAuditByRuleNo(1, DroolsCampaignAudit.PastBenefitsCriteriasAreSatisfied);
		update($event);
end

rule "Campaign(7)-Rule1-Sec6(BenefitLimit)"
	when
		$event : DroolsCampaignEvent(getDroolsCampaignAuditByRuleNo(1) == DroolsCampaignAudit.PastBenefitsCriteriasAreSatisfied)
	then
		$event.updateDroolsCampaignAuditByRuleNo(1, DroolsCampaignAudit.BenefitLimitCriteriasAreSatisfied);
		update($event);
end

rule "Campaign(7)-Rule1-Sec7(Recurrence)"
	when
		$event : DroolsCampaignEvent(getDroolsCampaignAuditByRuleNo(1) == DroolsCampaignAudit.BenefitLimitCriteriasAreSatisfied)
	then
		$event.updateDroolsCampaignAuditByRuleNo(1, DroolsCampaignAudit.RecurrenceCriteriasAreSatisfied);
		update($event);
end

rule "Campaign(7)-Rule1-Sec8(Final)"
	when
		$event : DroolsCampaignEvent(getDroolsCampaignAuditByRuleNo(1) == DroolsCampaignAudit.RecurrenceCriteriasAreSatisfied)
	then
		$event.updateDroolsCampaignAuditByRuleNo(1, DroolsCampaignAudit.AllRuleCriteriasAreSatisfied);
		update($event);
		$event.addDroolsCampaignMatch("7","1","1");
end